# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Selkup spellchecker"
sel = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Selkup, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
sel = "TRANSLATE: A spellchecker for Selkup, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.sel"

[windows]
system_product_code = "{33B2B861-6B2E-47DC-859D-4A4ABC42B4C0}_is1"
legacy_product_codes = [
    { value = "BFFD8709-CD82-4084-A202-E19619582217", kind = "nsis" },
    { value = "E82D3310-C767-44EF-802B-90842D315F57", kind = "nsis" }
]

[package.speller]
name = "Selkup"
version = "0.1.1"

[package.grammar]
name = "Selkup"
version = "0.1.0"

[package.tts-textproc]
name = "Selkup"
version = "0.1.0"

[package.hyphenator]
name = "Selkup"
version = "0.1.0"
