template = "https://github.com/giellalt/template-lang-und"
rev_id = 254
template_sha = "9eb2a95995f59cb63a159a5cc7bcce8f049babe4"

[replacements]
__GLOTTOLOG_ID__ = "selk1253"
__REPO__ = "lang-sel"
__UND2C__ = "sel"
__UNDEFINED__ = "Selkup"
__UND__ = "sel"
